[package]
name = "rust_reader"
version = "0.1.0"
authors = ["Eh2406 <YeomanYaacov@gmail.com>"]

[dependencies]
winapi = "0.2.6"
ole32-sys = "0.2.0"
user32-sys = "0.1.2"
kernel32-sys = "0.2.1"
clipboard-win = "1.7.1"
rustc-serialize = "0.3"
preferences = "0.5.0"
quickcheck = "0.2.27"
unicode-segmentation = "0.1.2"
