[package]
name = "rust_reader"
version = "0.1.0"
authors = ["Eh2406 <YeomanYaacov@gmail.com>"]

[dependencies]
winapi = "0.2.5"
ole32-sys = "0.2.0"
user32-sys = "0.1.2"
clipboard-win = "1.6.2"
rustc-serialize = "0.3"
