[package]
name = "rust_reader"
version = "0.1.0"
authors = ["Eh2406 <YeomanYaacov@gmail.com>"]

[dependencies]
winapi = "*"
ole32-sys = "*"
user32-sys = "*"
kernel32-sys = "*"
clipboard-win = "*"
serde_derive = "*"
serde = "*"
preferences = { git = "https://github.com/Eh2406/preferences-rs", branch = "patch-1"}
unicode-segmentation = "*"
regex = "*"
itertools = "*"
average = "*"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
quickcheck = "*"
lazy_static = "*"

[profile.release]
debug = true

[profile.bench]
debug = true
