[package]
name = "rust_reader"
version = "0.1.0"
authors = ["Eh2406 <YeomanYaacov@gmail.com>"]

[dependencies]
winapi = "0.2"
ole32-sys = "0.2.0"
user32-sys = "0.2.0"
kernel32-sys = "0.2.2"
clipboard-win = "2.0.0"
serde_derive = "0.9.13"
serde = "0.9.13"
preferences = "1.1.0"
unicode-segmentation = "1.1.0"
regex = "0.2"
itertools = "0.6.0"

[dev-dependencies]
quickcheck = "0.4.1"
lazy_static = "0.2.8"
